'use client';

/**
 * Quick Observations - Voice-Enabled Data Collection
 * COMPETITIVE ADVANTAGE: Capture observations in 30 seconds vs 10 minutes typing
 *
 * Teacher workflow:
 * 1. Click microphone
 * 2. Say: "Johnny struggled with reading comprehension during small group"
 * 3. AI auto-categorizes by student, skill, and IEP goal
 * 4. Done. No typing.
 */

import { useState, useEffect } from 'react';
import {
  MicrophoneIcon,
  StopIcon,
  CheckCircleIcon,
  UserIcon,
  CalendarIcon,
  TagIcon,
  SparklesIcon,
} from '@heroicons/react/24/outline';

interface Observation {
  id: string;
  studentName: string;
  timestamp: Date;
  content: string;
  category: string;
  relatedGoals: string[];
  autoGenerated: boolean;
}

export default function QuickObservationsPage() {
  const [isRecording, setIsRecording] = useState(false);
  const [transcript, setTranscript] = useState('');
  const [observations, setObservations] = useState<Observation[]>([]);
  const [recognition, setRecognition] = useState<any>(null);
  const [processing, setProcessing] = useState(false);
  const [selectedStudent, setSelectedStudent] = useState('');

  // Initialize speech recognition
  useEffect(() => {
    if (typeof window !== 'undefined' && ('webkitSpeechRecognition' in window || 'SpeechRecognition' in window)) {
      const SpeechRecognition = (window as any).webkitSpeechRecognition || (window as any).SpeechRecognition;
      const recognitionInstance = new SpeechRecognition();

      recognitionInstance.continuous = false;
      recognitionInstance.interimResults = true;
      recognitionInstance.lang = 'en-US';

      recognitionInstance.onresult = (event: any) => {
        const current = event.resultIndex;
        const transcriptText = event.results[current][0].transcript;
        setTranscript(transcriptText);
      };

      recognitionInstance.onend = () => {
        setIsRecording(false);
        if (transcript) {
          processObservation(transcript);
        }
      };

      recognitionInstance.onerror = (event: any) => {
        console.error('Speech recognition error:', event.error);
        setIsRecording(false);
      };

      setRecognition(recognitionInstance);
    }
  }, []);

  const startRecording = () => {
    if (recognition) {
      setTranscript('');
      recognition.start();
      setIsRecording(true);
    }
  };

  const stopRecording = () => {
    if (recognition) {
      recognition.stop();
      setIsRecording(false);
    }
  };

  const processObservation = async (text: string) => {
    setProcessing(true);

    try {
      // Call AI to categorize and extract metadata
      const response = await fetch('/api/ai/process-observation', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text, studentId: selectedStudent }),
      });

      if (response.ok) {
        const data = await response.json();

        const newObservation: Observation = {
          id: Date.now().toString(),
          studentName: data.studentName || 'Unknown Student',
          timestamp: new Date(),
          content: text,
          category: data.category || 'General',
          relatedGoals: data.relatedGoals || [],
          autoGenerated: true,
        };

        setObservations([newObservation, ...observations]);
        setTranscript('');
      }
    } catch (error) {
      console.error('Failed to process observation:', error);

      // Fallback: Save without AI processing
      const newObservation: Observation = {
        id: Date.now().toString(),
        studentName: selectedStudent || 'Unknown Student',
        timestamp: new Date(),
        content: text,
        category: 'Uncategorized',
        relatedGoals: [],
        autoGenerated: false,
      };

      setObservations([newObservation, ...observations]);
      setTranscript('');
    } finally {
      setProcessing(false);
    }
  };

  const mockStudents = [
    'Select a student...',
    'Johnny Doe',
    'Sarah Smith',
    'Michael Johnson',
    'Emily Davis',
    'David Wilson',
  ];

  return (
    <div className="min-h-screen bg-gray-50 pb-20">
      {/* Header */}
      <div className="bg-gradient-to-r from-purple-600 to-blue-600 text-white shadow-lg">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-3xl font-bold">Quick Observations</h1>
              <p className="mt-2 text-purple-100">
                🎤 Capture observations with your voice—no typing needed
              </p>
            </div>
            <div className="bg-white/10 backdrop-blur-sm rounded-lg px-6 py-3 border border-white/20">
              <p className="text-sm font-medium">Time Saved Today</p>
              <p className="text-3xl font-bold">2.5 hours</p>
            </div>
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Recording Panel */}
          <div className="lg:col-span-1">
            <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6 sticky top-8">
              <h2 className="text-lg font-semibold text-gray-900 mb-4">Record Observation</h2>

              {/* Student Selector */}
              <div className="mb-6">
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Student
                </label>
                <select
                  value={selectedStudent}
                  onChange={(e) => setSelectedStudent(e.target.value)}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-purple-500 focus:border-transparent"
                >
                  {mockStudents.map((student) => (
                    <option key={student} value={student}>
                      {student}
                    </option>
                  ))}
                </select>
              </div>

              {/* Recording Interface */}
              <div className="text-center">
                <button
                  onClick={isRecording ? stopRecording : startRecording}
                  disabled={!selectedStudent || selectedStudent === 'Select a student...'}
                  className={`relative inline-flex items-center justify-center w-32 h-32 rounded-full transition-all ${
                    isRecording
                      ? 'bg-red-500 hover:bg-red-600 shadow-lg shadow-red-500/50'
                      : 'bg-purple-600 hover:bg-purple-700 shadow-lg shadow-purple-500/50'
                  } disabled:bg-gray-300 disabled:cursor-not-allowed disabled:shadow-none`}
                >
                  {isRecording ? (
                    <>
                      <StopIcon className="h-12 w-12 text-white" />
                      <span className="absolute -bottom-1 -right-1 flex h-6 w-6">
                        <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-red-400 opacity-75"></span>
                        <span className="relative inline-flex rounded-full h-6 w-6 bg-red-500"></span>
                      </span>
                    </>
                  ) : (
                    <MicrophoneIcon className="h-12 w-12 text-white" />
                  )}
                </button>

                <p className="mt-4 text-sm font-medium text-gray-700">
                  {isRecording ? 'Recording... Click to stop' : 'Click to record'}
                </p>

                {/* Live Transcript */}
                {transcript && (
                  <div className="mt-6 p-4 bg-purple-50 rounded-lg border border-purple-200">
                    <p className="text-sm text-purple-900">{transcript}</p>
                  </div>
                )}

                {processing && (
                  <div className="mt-6 flex items-center justify-center gap-2 text-purple-600">
                    <SparklesIcon className="h-5 w-5 animate-spin" />
                    <span className="text-sm font-medium">Processing with AI...</span>
                  </div>
                )}
              </div>

              {/* Quick Tips */}
              <div className="mt-8 p-4 bg-blue-50 rounded-lg border border-blue-200">
                <h3 className="text-sm font-semibold text-blue-900 mb-2">💡 Quick Tips</h3>
                <ul className="text-xs text-blue-800 space-y-1">
                  <li>• Say the student's name first</li>
                  <li>• Mention the activity or subject</li>
                  <li>• Describe what you observed</li>
                  <li>• AI will auto-categorize it!</li>
                </ul>
              </div>
            </div>
          </div>

          {/* Observations List */}
          <div className="lg:col-span-2">
            <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
              <div className="flex items-center justify-between mb-6">
                <h2 className="text-lg font-semibold text-gray-900">Today's Observations</h2>
                <span className="px-3 py-1 bg-purple-100 text-purple-700 text-sm font-medium rounded-full">
                  {observations.length} recorded
                </span>
              </div>

              {observations.length === 0 ? (
                <div className="text-center py-12">
                  <MicrophoneIcon className="h-16 w-16 text-gray-300 mx-auto mb-4" />
                  <p className="text-gray-500 font-medium">No observations yet</p>
                  <p className="text-gray-400 text-sm mt-1">Click the microphone to record your first observation</p>
                </div>
              ) : (
                <div className="space-y-4">
                  {observations.map((obs) => (
                    <div
                      key={obs.id}
                      className="p-4 border border-gray-200 rounded-lg hover:shadow-md transition-shadow"
                    >
                      <div className="flex items-start justify-between mb-2">
                        <div className="flex items-center gap-2">
                          <UserIcon className="h-5 w-5 text-purple-600" />
                          <span className="font-semibold text-gray-900">{obs.studentName}</span>
                          {obs.autoGenerated && (
                            <span className="inline-flex items-center gap-1 px-2 py-0.5 bg-purple-100 text-purple-700 text-xs font-medium rounded">
                              <SparklesIcon className="h-3 w-3" />
                              AI Categorized
                            </span>
                          )}
                        </div>
                        <div className="flex items-center gap-1 text-xs text-gray-500">
                          <CalendarIcon className="h-4 w-4" />
                          {obs.timestamp.toLocaleTimeString()}
                        </div>
                      </div>

                      <p className="text-gray-700 mb-3">{obs.content}</p>

                      <div className="flex items-center gap-4">
                        <div className="flex items-center gap-1 text-sm">
                          <TagIcon className="h-4 w-4 text-blue-500" />
                          <span className="text-gray-600">{obs.category}</span>
                        </div>

                        {obs.relatedGoals.length > 0 && (
                          <div className="flex items-center gap-2">
                            <CheckCircleIcon className="h-4 w-4 text-green-500" />
                            <span className="text-sm text-gray-600">
                              {obs.relatedGoals.length} related goals
                            </span>
                          </div>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </div>

            {/* Stats Cards */}
            <div className="grid grid-cols-3 gap-4 mt-6">
              <div className="bg-gradient-to-br from-green-50 to-green-100 border border-green-200 rounded-lg p-4">
                <p className="text-sm font-medium text-green-800">This Week</p>
                <p className="text-2xl font-bold text-green-900">{observations.length}</p>
                <p className="text-xs text-green-700 mt-1">observations</p>
              </div>

              <div className="bg-gradient-to-br from-blue-50 to-blue-100 border border-blue-200 rounded-lg p-4">
                <p className="text-sm font-medium text-blue-800">Time Saved</p>
                <p className="text-2xl font-bold text-blue-900">2.5h</p>
                <p className="text-xs text-blue-700 mt-1">vs typing</p>
              </div>

              <div className="bg-gradient-to-br from-purple-50 to-purple-100 border border-purple-200 rounded-lg p-4">
                <p className="text-sm font-medium text-purple-800">Auto-Tagged</p>
                <p className="text-2xl font-bold text-purple-900">
                  {observations.filter(o => o.autoGenerated).length}
                </p>
                <p className="text-xs text-purple-700 mt-1">by AI</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
